server:
  port: 8000
  error:
    path: /error
    include-exception: false
    include-stacktrace: never
    whitelabel.enabled: false

spring:
  servlet:
    multipart.enabled: true
    multipart.max-file-size: 10MB
    multipart.max-request-size: 10MB
  web:
    resources:
      cache.period: 0
      static-locations: file:src/main/resources/static
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates
    suffix: .html
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        order_inserts: true
        order_updates: true
        jdbc.batch_size: 10000
  cache:
    type: redis
    cache-names: store_cache
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/2302_exhibition_ticket_db
    username: root
    password: dreamy
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: exhibition_ticket_cp
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
        rewriteBatchedStatements: true

logging:
  level:
    org.hibernate.SQL: debug